version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "{{ cookiecutter.backend_port }}:{{ cookiecutter.backend_port }}"
    environment:
      - ENVIRONMENT=development
      - PORT={{ cookiecutter.backend_port }}
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port {{ cookiecutter.backend_port }} --reload

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "{{ cookiecutter.frontend_port }}:{{ cookiecutter.frontend_port }}"
    environment:
      - REACT_APP_API_URL=http://localhost:{{ cookiecutter.backend_port }}
    depends_on:
      - backend