version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:{{ cookiecutter.backend_port }}"
    environment:
      - ENVIRONMENT=production
      - PORT={{ cookiecutter.backend_port }}
    
  # For development, we can still keep separate services
  backend-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    volumes:
      - ./backend:/app/backend
    ports:
      - "{{ cookiecutter.backend_port }}:{{ cookiecutter.backend_port }}"
    environment:
      - ENVIRONMENT=development
      - PORT={{ cookiecutter.backend_port }}
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port {{ cookiecutter.backend_port }} --reload
    profiles: ["dev"]

  frontend-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "{{ cookiecutter.frontend_port }}:{{ cookiecutter.frontend_port }}"
    environment:
      - REACT_APP_API_URL=http://localhost:{{ cookiecutter.backend_port }}
    command: npm start
    depends_on:
      - backend-dev
    profiles: ["dev"]